### ISSUE TITLE
Swing adjusting

### ISSUE THREAD

**Issue by AidanTheSerg** [Reezonate/EasyOffset#11]
When triyng to adjust your swing, the offset wont let you since the wheel is at the bottom where you stand.
![Screenshot_20221025_144650](https://user-images.githubusercontent.com/116653831/197790762-852c862c-7cae-419a-943a-3824774a6222.png)

**Comment by Reezonate** [comment]
I don't quite understand what is going on with your screenshot and description, can you please explain the issue in more details? Steps to reproduce?

**Comment by AidanTheSerg** [comment]
Basically when I try to do the swing bench adjustment for trying to fix the swinging, the wheel of it is at the feet of where you stand constantly which causes none of the adjustments to work

**Comment by AidanTheSerg** [comment]
Im not sure how it happened but started after adding mods

**Comment by Reezonate** [comment]
This never happened before with anyone, may be mods installation problem. Please try again, close the game normally and send me the log file. (`Beat Saber/logs/_latest.log`)

**Comment by AidanTheSerg** [comment]
> This never happened before with anyone, may be mods installation problem. Please try again, close the game normally and send me the log file. (`Beat Saber/logs/_latest.log`)

[_latest.log](https://github.com/Reezonate/EasyOffset/files/9876638/_latest.log)

**Comment by Reezonate** [comment]
There is an issue with your Saber Factory config file. Remove SaberFactory.json from the UserData folder (backup it somewhere) and try again

**Comment by AidanTheSerg** [comment]
Will try that now

**Comment by Reezonate** [comment]
Try also removing SaberFactory folder from the UserData directory. Seems like corrupted config is located there

**Comment by AidanTheSerg** [comment]
Removing them 2 have seem to fixed it, thank you.
