### ISSUE TITLE
Bug: Unable to adjust rotation

### ISSUE THREAD

**Issue by ayesc9000** [Reezonate/EasyOffset#14]
I can adjust positioning just fine, but when i adjust rotation at all, the sliders become disabled and I cannot adjust rotation anymore without restarting beat saber.

![20230202181726_1](https://user-images.githubusercontent.com/29239155/216472911-cf876330-8d37-4d31-99b4-eb3fbe514d77.jpg)

**Comment by Reezonate** [comment]
To access sliders you need to first set a reference using the SwingBenchmark mode

Read the instructions on github or watch the in-game user guide please:
https://github.com/Reezonate/EasyOffset#rotation-adjustment-mode

**Comment by ayesc9000** [comment]
Okay. Could you at least change the behaviour to display a notice instead of just disabling the sliders after adjusting them? That would make it a lot more intuitive.

**Comment by Reezonate** [comment]
There are 2 notices already + complete video guide built into the mod. I don't think it is necessary to add more
![image](https://user-images.githubusercontent.com/91229110/216750624-1babbc39-3685-4c50-9a96-ac8b6d2e020f.png)
![image](https://user-images.githubusercontent.com/91229110/216750635-69861be7-013b-4c3f-b46c-a8c0b0da0809.png)
