### ISSUE TITLE
BUG: EasyOffset don't show up in the game (BS Version 1.29.1)

### ISSUE THREAD

**Issue by Archycmd** [Reezonate/EasyOffset#18]
when installed, there is no in game (or outside) way to access the mod. I tried to have only EasyOffset and the minimal requirement to be sure it's not a mod incompatibility. Can't really show picture as there noting to show except noting. (Is using BSManager)

**Comment by Reezonate** [comment]
you probably need to enable it in the mod settings

**Comment by Archycmd** [comment]
thx for the answer but, what mod settings? there is no mod settings available anywhere that I look.

**Comment by Archycmd** [comment]
oh. why is it not enabled by default? but yes that was the solution. thx for the answer
