### ISSUE TITLE
Suggestion: add explain of how to convert the saved preset config to stock game offset setting

### ISSUE THREAD

**Issue by lixiangwuxian** [Reezonate/EasyOffset#24]
After tired of the latency of the wireless streaming in steam version, I recently bought the quest version of the game. 

Sadly, I found there is no such mod on quest to adjust saber so easily. 

But without a suitable offset, it is hard to enjoy the game. 

So I wonder, is there a convert algorithm that can convert the saved offset preset to in game settings (position XYZ & rotation XYZ)?

Thank you.

**Comment by Reezonate** [comment]
You can try to [export your config to base game](https://github.com/Reezonate/EasyOffset?tab=readme-ov-file#export) on pc, and use resulting values on quest. But I have no idea if base game settings are the same between pc and quest

**Comment by lixiangwuxian** [comment]
It works perfect.
Thank you for the help again🫡
