### ISSUE TITLE
Suggestion: Can we add a new function to show saber rotz? work like controller setting helper&saber tailor

### ISSUE THREAD

**Issue by RuoChennn** [Reezonate/EasyOffset#25]
Can we add a new function to show saber rotz? work like controller setting helper&saber tailor

or add a manualy rotz visual adjust interface?

**Comment by Reezonate** [comment]
RotZ in base game and saber tailor changes the way how other settings work, so it makes sense to display it in controller settings helper

However, in EasyOffset RotZ has no real meaning. It changes nothing and is purely cosmetic. Are you aware of this and want it for cosmetic purposes?
