### ISSUE TITLE
Feature request: Support for 1.36.0

### ISSUE THREAD

**Issue by f1amy** [Reezonate/EasyOffset#26]
Hey, I just wanted to ask if there will be 1.36.0 support.
Due to the nature of this mod and recent disabling of exporting for controller settings, I depend on this mod to play the game.

P.S. This is the best mod for Beat Saber, I owe it much of my skill improvement over the time I've used it.

**Comment by Reezonate** [comment]
[latest release for 1.35](https://github.com/Reezonate/EasyOffset/releases/tag/v2.1.8) seems to still work fine 🤔

Unfortunately I'll not be able to use VR for at least 3 days to confirm

**Comment by f1amy** [comment]
Just tried it out and it works for me (just controller settings), now I feel dumb for not trying this first 😅

Would still very like to have an official support and continued development
