### ISSUE TITLE
Add option for -vrmode oculus basegame settings export

### ISSUE THREAD

**Issue by byhemechi** [Reezonate/EasyOffset#7]

**Comment by Reezonate** [comment]
Export should work regardless of the VR platform used.  Are you using v2.0.1 (latest export bug fix)? 

But it is possible that I introduced some bugs with the addition of ZRot support in v2.0. Sadly I have no oculus headset and can't test vrmode export myself

**Comment by byhemechi** [comment]
i'll google around a bit and try find out what the exact difference is
