### ISSUE TITLE
Feature Request: World offset (ike in sabertailor)

### ISSUE THREAD

**Issue by byhemechi** [Reezonate/EasyOffset#8]
For some reason index tracking puts both of my controllers like 5 cm to the right. it would be very nice to be able to correct for this

**Comment by Reezonate** [comment]
Sounds like a headset offset issue (hardware/driver). I don't like the idea of the world offset feature being useless for 99.9% of the users, while adding a lot of confusion to already complex process for everyone. 

Also it is not the way how people should fix hardware problems like this tbh. But if you have no other choice - separate mod for this sounds like a better way to handle it

**Comment by byhemechi** [comment]
yup, that sounds pretty fair.

**Comment by YoLeax** [comment]
@byhemechi Hi, I made a mod to independently adjust the world position offsets of the left and right sabers, and it can be used together with easy offset. If you still need this, check out this repository:
https://github.com/YoLeax/BeatSaber-WorldPosOffset
