### ISSUE TITLE
Feature Request - Add PiMax Sword Model

### ISSUE THREAD

**Issue by tophattwaffle** [Reezonate/EasyOffset#9]
Would it be possible to add the PiMax Sword controllers to the in-game preview?
[pimaxSwords_SteamVR_OBJ.zip](https://github.com/Reezonate/EasyOffset/files/8767777/pimaxSwords_SteamVR_OBJ.zip)

**Comment by Reezonate** [comment]
Sure, but I'll need your help to check the position of the model and input buttons

**Comment by tophattwaffle** [comment]
I'd be more than happy to assist.

**Comment by Reezonate** [comment]
tried my best to align the existing model to your photos. Available in the latest release (v2.1.0)
